apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-teste-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-teste
  template:
    metadata:
      labels:
        app: keda-teste
    spec:
      containers:
        - name: keda-teste
          image: 540373670534.dkr.ecr.us-east-2.amazonaws.com/keda-teste:2.0.0
          env:
            - name: AWS_REGION
              value: us-east-2
            - name: AWS_SQS_QUEUE_URL
              value: https://sqs.us-east-2.amazonaws.com/540373670534/sqs-inicio-processo
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
